pipeline {

    agent any

    stages {
        stage ('build') {
            steps{
                sh './jenkins/build/mvn.sh mvn -B -DskipTests clean package'
            }
            post {
                success {
                    archiveArtifacts artifacts: 'java-app/target/*.war', fingerprint: true
                }
            }
        }

        stage('Test') {
                steps {
                    sh './jenkins/test/mvn.sh mvn test'
                }
            }
        stage('Push') {
                steps {
                    sh './jenkins/push/push.sh'
                }
            }
        stage('Deploy') {
                steps {
                    sh './jenkins/deploy/deploy.sh'
                }
            }
    }
}